import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { once } from 'node:events';
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { expect } from '@playwright/test';
import { createApp } from '../server/app.mjs';
import { graphicsOnlyPdf } from './fixtures/scan-browser.mjs';

export async function vaultWorkflow({context,root,onPreview}) {
  const fixture=await mkdtemp(path.join(tmpdir(),'paperdesk-vault-browser-'));
  const vaultDir=path.join(fixture,'精读知识库'), dataDir=path.join(fixture,'cache');
  await mkdir(path.join(vaultDir,'.obsidian'),{recursive:true});
  const sourceRelative='已有资料/模拟电路/阅读 #示例.pdf', otherRelative='另一目录/阅读 #示例.pdf';
  const sourcePdf=path.join(vaultDir,sourceRelative), otherPdf=path.join(vaultDir,otherRelative);
  const sourceBytes=await readFile(path.join(root,'public/examples/reading-demo.pdf')), otherBytes=graphicsOnlyPdf();
  await mkdir(path.dirname(sourcePdf),{recursive:true});await mkdir(path.dirname(otherPdf),{recursive:true});
  await writeFile(sourcePdf,sourceBytes);await writeFile(otherPdf,otherBytes);
  const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
  const runtime=createApp({vaultDir,dataDir});await runtime.ready;
  const server=runtime.app.listen(0,'127.0.0.1');await once(server,'listening');
  const base=`http://127.0.0.1:${server.address().port}`;
  const page=await context.newPage();
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const uploads=[];page.on('request',request=>{if(request.method()==='POST'&&request.url()===`${base}/api/documents`)uploads.push(request.url());});
  const documentList=async()=>(await(await fetch(`${base}/api/documents`)).json()).documents;
  let release;
  try {
    await page.goto(base);await page.waitForLoadState('networkidle');
    await page.getByRole('button',{name:'资料位置',exact:true}).click();
    const dialog=page.getByRole('dialog',{name:'资料位置',exact:true});
    await expect(dialog).toContainText('Obsidian 仓库');await expect(dialog).toContainText('精读知识库');
    const rules=dialog.getByRole('region',{name:'使用规则',exact:true});
    await expect(rules).toContainText('笔记正文可在 Paperdesk 和 Obsidian 两边编辑');
    await expect(rules).toContainText('批注、标题和分类在 Paperdesk 修改');
    await expect(rules).toContainText('PDF 留在原目录');
    await expect(rules).toContainText('移动或改名后，暂需恢复原路径');
    await expect(rules).toContainText('同一篇文献错开编辑');
    await expect(rules).toContainText('换设备时等同步完成');
    await expect(rules).toContainText('冲突不会自动合并');
    await expect(dialog.getByRole('button',{name:'在 Obsidian 中打开笔记'})).toBeDisabled();
    await dialog.getByRole('button',{name:'关闭资料位置'}).click();
    await expect(page.getByLabel('选择 PDF 文件')).toHaveCount(0);
    await expect(page.getByRole('button',{name:'打开阅读示例',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'选择 Obsidian PDF',exact:true}).click();
    const picker=page.getByRole('dialog',{name:'选择 Obsidian PDF',exact:true});
    const sourceButton=picker.getByRole('button',{name:`打开 PDF：${sourceRelative}`,exact:true});
    const otherButton=picker.getByRole('button',{name:`打开 PDF：${otherRelative}`,exact:true});
    await expect(sourceButton).toBeVisible();await expect(otherButton).toBeVisible();
    await expect(sourceButton).toContainText('已有资料/模拟电路');await expect(otherButton).toContainText('另一目录');
    await onPreview?.(page,'vault-pdf-picker-wide');
    assert.equal((await documentList()).length,0,'Listing existing PDFs must not create document associations');
    await picker.getByRole('button',{name:'取消',exact:true}).click();
    await expect(picker).toHaveCount(0);assert.equal((await documentList()).length,0);
    await page.getByRole('button',{name:'选择第一篇 Obsidian PDF',exact:true}).click();
    await expect(sourceButton).toBeVisible();
    await picker.getByRole('button',{name:'关闭 PDF 选择器',exact:true}).click();
    await expect(picker).toHaveCount(0);assert.equal((await documentList()).length,0);
    await page.getByRole('button',{name:'选择第一篇 Obsidian PDF',exact:true}).click();
    await expect(sourceButton).toBeVisible();
    await picker.getByRole('textbox',{name:'搜索 Obsidian PDF',exact:true}).fill('模拟电路');
    await expect(sourceButton).toBeVisible();await expect(otherButton).toHaveCount(0);
    const initialViewport=page.viewportSize();await page.setViewportSize({width:640,height:720});
    const pickerBounds=await picker.boundingBox();assert.ok(pickerBounds.x>=0&&pickerBounds.x+pickerBounds.width<=640&&pickerBounds.height<=680);
    await onPreview?.(page,'vault-pdf-picker-narrow');
    await page.setViewportSize(initialViewport||{width:1440,height:1000});
    const selected=page.waitForResponse(response=>response.url()===`${base}/api/vault/pdfs/open`&&response.request().method()==='POST');
    await sourceButton.click();const selectedResponse=await selected;assert.equal(selectedResponse.status(),201);
    assert.equal(selectedResponse.request().postDataJSON().path,sourceRelative);
    const doc=(await selectedResponse.json()).document;
    await expect(picker).toHaveCount(0);
    const editor=page.getByRole('textbox',{name:'笔记',exact:true});await expect(editor).toBeVisible();
    await expect(page.locator('.vault-note-rule')).toHaveText('正文可在两边编辑，批注由 Paperdesk 管理。');
    await expect(page.getByLabel('PDF 第 1 页',{exact:true})).toBeVisible();
    await editor.fill('Paperdesk 初始理解');await page.getByRole('button',{name:'保存',exact:true}).click();
    await expect(page.locator('.save-row [role="status"]')).toHaveText('已保存到 Obsidian 仓库');
    const note=path.join(vaultDir,'Paperdesk','Notes',`${doc.id}.md`);
    assert.equal(hash(await readFile(sourcePdf)),hash(sourceBytes));assert.equal(hash(await readFile(otherPdf)),hash(otherBytes));
    const managedPdfs=await readdir(path.join(vaultDir,'Paperdesk','PDFs')).catch(error=>{if(error.code==='ENOENT')return[];throw error;});
    assert.deepEqual(managedPdfs,[],'Selecting an existing PDF must never create a Paperdesk/PDFs copy');
    await page.getByRole('button',{name:'选择 Obsidian PDF',exact:true}).click();
    await expect(sourceButton).toContainText('已关联');
    const reopened=page.waitForResponse(response=>response.url()===`${base}/api/vault/pdfs/open`&&response.request().method()==='POST');
    await sourceButton.click();const reopenedResponse=await reopened;assert.equal(reopenedResponse.status(),200);
    assert.equal((await reopenedResponse.json()).document.id,doc.id);assert.equal((await documentList()).length,1);
    await expect(picker).toHaveCount(0);
    await expect(editor).toHaveValue('Paperdesk 初始理解');
    const heading=page.locator('.textLayer span').filter({hasText:/^Reading with intention$/});await expect(heading).toBeVisible();
    await expect(page.locator('.pdf-paper')).not.toHaveClass(/is-loading/);
    const box=await heading.boundingBox();await page.mouse.move(box.x+1,box.y+box.height/2);await page.mouse.down();
    await page.mouse.move(box.x+box.width-1,box.y+box.height/2,{steps:5});await page.mouse.up();
    await page.getByRole('button',{name:'高亮并批注',exact:true}).click();
    const annotationDialog=page.getByRole('dialog',{name:/高亮与批注/});
    await annotationDialog.getByRole('textbox',{name:'批注评论',exact:true}).fill('原位 PDF 的真实文字批注。');
    await annotationDialog.getByRole('button',{name:'保存批注',exact:true}).click();await expect(annotationDialog).toHaveCount(0);
    assert.ok((await readFile(note,'utf8')).includes('原位 PDF 的真实文字批注。'));
    await page.locator('.annotation-card').getByRole('button',{name:'编辑批注',exact:true}).click();
    const annotationEditor=page.getByRole('textbox',{name:'编辑批注内容',exact:true});await annotationEditor.fill('选择前仍未保存的评论草稿');
    await page.getByRole('button',{name:'选择 Obsidian PDF',exact:true}).click();
    await expect(page.locator('.toast')).toContainText('仍有未保存的批注评论');await expect(picker).toHaveCount(0);
    await expect(annotationEditor).toHaveValue('选择前仍未保存的评论草稿');assert.equal((await documentList()).length,1);
    await page.locator('.annotation-card').getByRole('button',{name:'放弃草稿',exact:true}).click();
    await page.locator('.panel-tabs button').first().click();
    await page.route(`${base}/api/documents/${doc.id}`,async route=>{
      if(route.request().method()==='PATCH'&&typeof route.request().postDataJSON()?.notesZh==='string')await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'隔离验证：选择前笔记保存失败'})});
      else await route.continue();
    });
    await editor.fill('选择 PDF 前必须保留的未保存笔记');
    await page.getByRole('button',{name:'选择 Obsidian PDF',exact:true}).click();
    await expect(page.locator('.toast')).toContainText('选择前笔记保存失败');await expect(picker).toHaveCount(0);
    await expect(editor).toHaveValue('选择 PDF 前必须保留的未保存笔记');assert.equal((await documentList()).length,1);
    await page.unroute(`${base}/api/documents/${doc.id}`);
    await editor.fill('Paperdesk 初始理解');await page.getByRole('button',{name:'保存',exact:true}).click();
    await expect(page.locator('.save-row [role="status"]')).toHaveText('已保存到 Obsidian 仓库');
    const dropped=await page.evaluateHandle(()=>{const data=new DataTransfer();data.items.add(new File(['%PDF-1.7'],'外部拖入.pdf',{type:'application/pdf'}));return data;});
    await page.locator('.app-shell').dispatchEvent('drop',{dataTransfer:dropped});await dropped.dispose();
    await expect(page.locator('.toast')).toContainText('请先把 PDF 放进 Obsidian');assert.deepEqual(uploads,[]);
    await writeFile(note,(await readFile(note,'utf8')).replace('Paperdesk 初始理解','Obsidian 修改：先核对工作条件。'));
    await expect(editor).toHaveValue('Obsidian 修改：先核对工作条件。',{timeout:12000});
    console.log('PASS: real existing-PDF picker/search/cancel, in-place rendering/annotation, repeat selection, save guards, no PDF copies and external-note readback');
    let entered;
    const captured=new Promise(resolve=>{entered=resolve;});
    const held=new Promise(resolve=>{release=resolve;});
    await page.route(`${base}/api/documents/${doc.id}`,async route=>{
      if(route.request().method()==='PATCH'&&typeof route.request().postDataJSON()?.notesZh==='string'){
        entered();await held;
      }
      await route.continue();
    });
    await editor.fill('Paperdesk 同时编辑的完整草稿');await captured;
    await writeFile(note,(await readFile(note,'utf8')).replace('Obsidian 修改：先核对工作条件。','Obsidian 同时编辑的正式正文'));
    await expect.poll(async()=>(await(await fetch(`${base}/api/documents/${doc.id}`)).json()).document.notesZh).toBe('Obsidian 同时编辑的正式正文');
    await expect(editor).toHaveValue('Paperdesk 同时编辑的完整草稿');
    release();release=null;
    await expect(page.locator('.notes-conflict')).toBeVisible({timeout:12000});
    const conflicts=path.join(vaultDir,'Paperdesk','Notes','Conflicts');
    await expect.poll(async()=>{try{return(await readdir(conflicts)).length;}catch{return 0;}}).toBeGreaterThan(0);
    assert.ok((await readFile(note,'utf8')).includes('Obsidian 同时编辑的正式正文'));
    await expect(page.locator('.save-row [role="status"]')).toHaveText('版本冲突，草稿已保留');
    await page.getByRole('button',{name:'保留草稿并载入已保存笔记'}).click();
    await expect(editor).toHaveValue('Obsidian 同时编辑的正式正文');
    const archived=await readdir(conflicts);assert.ok((await Promise.all(archived.map(name=>readFile(path.join(conflicts,name),'utf8')))).some(text=>text.includes('Paperdesk 同时编辑的完整草稿')));
    await page.unroute(`${base}/api/documents/${doc.id}`);
    let latestNotes='Obsidian 同时编辑的正式正文';
    for(const [label,damage,errorMatch] of [
      ['隐藏 JSON',source=>source.replace(/(<!-- paperdesk-state:v1\n)[^\n]*/, '$1{broken-json'),/JSON 已损坏/],
      ['批注区域',source=>source.replace('<!-- paperdesk-generated:start:v1 -->','<!-- damaged-generated-start -->'),/批注开始标记.*缺失/],
    ]){
      const original=await readFile(note,'utf8'), damaged=damage(original);
      assert.notEqual(damaged,original);
      const archivesBefore=(await readdir(conflicts)).sort();
      await writeFile(note,damaged);
      latestNotes=`${label}损坏时，这份完整本机草稿仍须保留。`;
      const rejected=page.waitForResponse(response=>response.url()===`${base}/api/documents/${doc.id}`&&response.request().method()==='PATCH'&&typeof response.request().postDataJSON()?.notesZh==='string');
      await editor.fill(latestNotes);await page.getByRole('button',{name:'保存',exact:true}).click();
      const failed=await rejected;assert.equal(failed.status(),409);
      const error=await failed.json();assert.match(error.error,errorMatch);
      assert.ok(!['NOTES_VERSION_CONFLICT','VAULT_FILE_CONFLICT'].includes(error.code));
      assert.notEqual(error.conflictPreserved,true);
      await expect(page.locator('.save-row [role="status"]')).toHaveText('保存失败，草稿已保留');
      await expect(page.locator('.notes-save-failure')).toHaveText(error.error);
      await expect(page.locator('.notes-conflict')).toHaveCount(0);
      await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled();
      await expect(editor).toHaveValue(latestNotes);
      const retained=await page.evaluate(id=>JSON.parse(localStorage.getItem(sessionStorage.getItem(`paperdesk-draft-slot-${id}`))||'null'),doc.id);
      assert.equal(retained.notesZh,latestNotes);
      assert.equal(await readFile(note,'utf8'),damaged,'Rejected saves must not rewrite a damaged formal file');
      assert.deepEqual((await readdir(conflicts)).sort(),archivesBefore,'A structural error must not be presented or archived as a note version conflict');
      await writeFile(note,original);
      await page.getByRole('button',{name:'保存',exact:true}).click();
      await expect(page.locator('.save-row [role="status"]')).toHaveText('已保存到 Obsidian 仓库');
      await expect(page.locator('.notes-save-failure')).toHaveCount(0);
      await expect(editor).toHaveValue(latestNotes);
      assert.ok((await readFile(note,'utf8')).includes(latestNotes));
      console.log(`PASS: damaged ${label} returns a retryable save failure, preserves the real file and local draft, and saves after repair`);
    }
    await page.getByRole('button',{name:'资料位置',exact:true}).click();
    await dialog.getByRole('button',{name:'重新读取仓库'}).click();await expect(dialog).toContainText('1 份文献');
    await expect(dialog.getByRole('button',{name:'在 Obsidian 中打开笔记'})).toBeEnabled();
    await onPreview?.(page,'vault-storage');
    await page.setViewportSize({width:640,height:720});
    const bounds=await dialog.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=640&&bounds.height<=680);
    await expect(rules).toContainText('冲突不会自动合并');
    await onPreview?.(page,'vault-storage-narrow');
    await dialog.getByRole('button',{name:'关闭资料位置'}).click();
    await page.reload();await expect(editor).toHaveValue(latestNotes);
    assert.equal(hash(await readFile(sourcePdf)),hash(sourceBytes));assert.equal(hash(await readFile(otherPdf)),hash(otherBytes));
    assert.deepEqual(await readdir(path.join(vaultDir,'Paperdesk','PDFs')).catch(error=>{if(error.code==='ENOENT')return[];throw error;}),[]);
    assert.deepEqual(uploads,[]);
    assert.deepEqual(errors,[]);
    console.log('PASS: simultaneous saves preserve both files and draft; usage rules, narrow storage dialog, refresh and reopen');
  } finally {
    release?.();await page.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await runtime.close();await rm(fixture,{recursive:true,force:true});
  }
}
