import { useState } from 'react';
import { createPortal } from 'react-dom';
import { api } from './api';

export default function KnowledgeExport({ selection, documentId, vaultMode, notify }) {
  const [draft,setDraft]=useState(null),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(null),[error,setError]=useState('');
  const send=async()=>{setBusy(true);setError('');const payload=attempt||{requestId:crypto.randomUUID(),documentId:draft.documentId,page:draft.page,rects:draft.rects,quote:draft.quote||'',comment,...(draft.preview?{image:draft.preview}:{})};setAttempt(payload);try{await api('/integrations/knowledge/export',{method:'POST',body:JSON.stringify(payload)});setDraft(null);setAttempt(null);notify('已发送到知识库；工作台打开后会自动接收。','success');}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <><button className="text-button" title={vaultMode?'保存原图、引文、想法及实际页码':'请先连接 Obsidian 知识库'} disabled={!vaultMode} onClick={()=>{setDraft({...selection,documentId});setComment('');setAttempt(null);setError('');}}>发送到知识库</button>{draft&&createPortal(<div className="modal-backdrop" onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'&&!busy)setDraft(null);}}><section className="annotation-modal" role="dialog" aria-modal="true" aria-label="发送到知识库"><div className="modal-heading"><h2>留给下一次理解 <small>第 {draft.page} 页</small></h2><button disabled={busy} onClick={()=>setDraft(null)} aria-label="关闭发送窗口">×</button></div>{draft.preview?<figure className="region-preview"><img src={draft.preview} alt="原始选区"/></figure>:<blockquote>{draft.quote}</blockquote>}<label htmlFor="knowledge-comment">你的想法（可选）</label><textarea id="knowledge-comment" autoFocus value={comment} disabled={busy||Boolean(attempt)} maxLength={20000} onChange={e=>setComment(e.target.value)}/>{error&&<p className="inline-error" role="alert">{error} 可按原内容重试；请求标识保持不变。</p>}<div className="modal-footer"><p>保留原图和来源，不会调用 AI。</p><button className="primary-button" disabled={busy} onClick={send}>{busy?'正在保存…':attempt?'重试发送':'发送到知识库'}</button></div></section></div>,document.body)}</>;
}
